### ISSUE TITLE
Crash on the Quarry.

### ISSUE THREAD

**Issue by CGLemon** [Nyanyan/Egaroucid#82] opened 2023-11-09 03:43 UTC
Egaroucid: [7ddfcc5](https://github.com/Nyanyan/Egaroucid/commit/7ddfcc5940ef12c2f1bd66f0748c2ca58bfa18f0)
Setting:  ```path_to_file/Egaroucid_console -gtp -l 12```
GUI: Quarry 0.2.0
GCC: ```g++ -O2 ./src/Egaroucid_console.cpp -o ./bin/Egaroucid_for_Console.out -mtune=native -march=native -mfpmath=both -pthread -std=c++17 -Wall -Wextra```
OS: Ubuntu 22.04
Description: Egaroucid may crash on the Quarry sometimes when I start the engine.

![Screenshot from 2023-11-09 11-37-24](https://github.com/Nyanyan/Egaroucid/assets/39462842/504e6609-97e5-4104-8065-04b77482d006)

**Comment by Nyanyan** [comment] 2023-11-13 03:30
@CGLemon Thank you for reporting a bug.
I tested it and succeeded to reproduce the crash bug, but still can't determine what went wrong.
I'll continue investigating. It can take long, but I'll be very pleased if you wait it.

**Comment by Nyanyan** [comment] 2024-04-09 08:25
This bug is resolved in version 7.0.0 (checked)

**Closed** 2024-04-17 14:23 UTC
Labels: Bug, Egaroucid_for_Console, User_Suggestion

**Comment by Nyanyan** [comment] 2024-04-17 14:25
@CGLemon I'm very sorry to be late, but this bug seems to be resolved and released new version. I'm pleased if you check it: https://github.com/Nyanyan/Egaroucid/releases/tag/console_v7.0.0
